# Generated by Django 2.2.16 on 2022-04-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentator',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='pub_date',
        ),
    ]
